### PR TITLE
Numpy notebooks and excercises

### PR DESCRIPTION
**Pull request by dansand**
Hi Louis. I added the notebooks describing the exercises I set in the course. I also created links through to  that material.

### CODE REVIEW

**Comment by lmoresi** [comment]
Just trying to rebuild the image - I will add your stuff and try again.

L

On 1 March 2016 at 9:51:35 PM, Dan Sandiford (notifications@github.commailto:notifications@github.com) wrote:

Hi Louis. I added the notebooks describing the exercises I set in the course. I also created links through to that material.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1

Commit Summary
-   Numpy notebooks and excercises

File Changes
-   A Notebooks/Numpy/GameOfLife.ipynbhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-0 (239)
-   A Notebooks/Numpy/Seasonal_averages.ipynbhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-1 (741)
-   M docs/Map.mdhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-2 (4)
-   M docs/index.mdhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-3 (1)

Patch Links:
-   https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.patch
-   https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.diff

—
Reply to this email directly or view it on GitHubhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.

---

Professor Louis Moresi
louis.moresi@unimelb.edu.auhttp://mailto:louis.moresi@unimelb.edu.au/
   (w) +61 3 8344 1217tel://8344%201217
   (m) +61 4 0333 1413tel://0333%201413
   (us) +1 505 349 4425tel://349%204425
www.moresi.infohttp://www.moresi.info/
www.underworldcode.org
http://www.underworldcode.org

**Comment by lmoresi** [comment]
Ridiculously slow internet uploading the image from my end. Hopefully it really will build automagically on Dit4c sometime during the night.

L

On 1 March 2016 at 9:52:44 PM, Louis Moresi (louis.moresi@unimelb.edu.aumailto:louis.moresi@unimelb.edu.au) wrote:

Just trying to rebuild the image - I will add your stuff and try again.

L

On 1 March 2016 at 9:51:35 PM, Dan Sandiford (notifications@github.commailto:notifications@github.com) wrote:

Hi Louis. I added the notebooks describing the exercises I set in the course. I also created links through to that material.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1

Commit Summary
-   Numpy notebooks and excercises

File Changes
-   A Notebooks/Numpy/GameOfLife.ipynbhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-0 (239)
-   A Notebooks/Numpy/Seasonal_averages.ipynbhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-1 (741)
-   M docs/Map.mdhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-2 (4)
-   M docs/index.mdhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-3 (1)

Patch Links:
-   https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.patch
-   https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.diff

—
Reply to this email directly or view it on GitHubhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.

---

Professor Louis Moresi
louis.moresi@unimelb.edu.auhttp://mailto:louis.moresi@unimelb.edu.au/
   (w) +61 3 8344 1217tel://8344%201217
   (m) +61 4 0333 1413tel://0333%201413
   (us) +1 505 349 4425tel://349%204425
www.moresi.infohttp://www.moresi.info/
www.underworldcode.org

## http://www.underworldcode.org

Professor Louis Moresi
louis.moresi@unimelb.edu.auhttp://mailto:louis.moresi@unimelb.edu.au/
   (w) +61 3 8344 1217tel://8344%201217
   (m) +61 4 0333 1413tel://0333%201413
   (us) +1 505 349 4425tel://349%204425
www.moresi.infohttp://www.moresi.info/
www.underworldcode.org
http://www.underworldcode.org

**Comment by lmoresi** [comment]
Dan - the machine appears to be malfunctioning !!

Sent from my iPhone

On 1 Mar 2016, at 21:51, Dan Sandiford <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Louis. I added the notebooks describing the exercises I set in the course. I also created links through to that material.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1

Commit Summary
-   Numpy notebooks and excercises

File Changes
-   A Notebooks/Numpy/GameOfLife.ipynbhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-0 (239)
-   A Notebooks/Numpy/Seasonal_averages.ipynbhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-1 (741)
-   M docs/Map.mdhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-2 (4)
-   M docs/index.mdhttps://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1/files#diff-3 (1)

Patch Links:
-   https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.patch
-   https://github.com/lmoresi/UoM-VIEPS-Intro-to-Python/pull/1.diff

**Comment by dansand** [comment]
Hi Louis, I'm ten minutes away - locked my keys inside,  no bike...

**Pull request merged**
